//Sasikaladevi Kumarasamy @ facebook_java_18

package lab6;

import java.util.Scanner;
// Random class generates random numbers from 0 to the number specified 
import java.util.Random;

// Application that simulates dice rolling. It asks the user for number of sides on each die 
//then generates random numbers on each die. Also it displays special messages on 
//specific combinations of numbers on each die.
// This program also checks for the validity of the user input and also the range
public class Lab6 {

	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		
		// print welcome message
		System.out.println("Welcome to the Grand Circus Casino!\n");
		int numberOfSides,randomOfDice1=0, randomOfDice2=0;
		
		String choice="y";
		
		// get input from the user
		numberOfSides = getIntInRange(sc, "How many sides should each die have(2-6)? ", 2, 6);
		
		do {
			// call the randomGeneraror method twice to get number for each die
			randomOfDice1=randomGenerator(numberOfSides);
			randomOfDice2=randomGenerator(numberOfSides);
			
			//print the random generated numbers for each die
			System.out.println(randomOfDice1 +"  and   "+ randomOfDice2);
			//System.out.println(randomOfDice2);
			specialMessage(randomOfDice1, randomOfDice2);
			
			// check if the user wants to roll the dice again?
			System.out.print("Do you want to roll again(yes/no)? ");
			choice=sc.next();
			
			sc.nextLine(); // clears the input stream
		}while(choice.toLowerCase().startsWith("y"));
		
		// display concluding message
		System.out.println("Thanks for playing!");
	}
	
	// generates a random number using Random class from the java.util library
	public static int randomGenerator(int numberOfSides) {
		int randomNumber=0;
		Random random = new Random();
		
		// since it might yield 0, adding 1 to it will avoid the 'zero' issue 
		randomNumber=random.nextInt(numberOfSides)+1;
		
		// returns the random number generated by the method
		return randomNumber;
	}
	
	
	// checks if the user entered input is integer or not
	private static int isInteger(Scanner sc, String msg) {
		int number =0;
		boolean validity = false;
		
		while(!validity) {
			System.out.print(msg);
			
			// checks if the input stream has an integer or not
			if(sc.hasNextInt()) {
				number = sc.nextInt();
				validity = true;
			}
			else {
				
				// if the user input is not an integer, display error message
				System.out.println("Not an integer! Please enter a valid integer.");
				continue;
			}
			sc.nextLine();
			
		}
		// returns the integer number
		return number;
	}
	
	// checks if the integer entered by the user is within range
	private static int getIntInRange(Scanner sc, String msg, int min, int max){
	    int d = 0;
	    boolean validity = false;
	    while (!validity){
	        d = isInteger(sc, msg) ;
	        // check if the entered value is greater than the minimum limit
	        if (d<min){
	            System.out.println("Please enter a number greater than " + min);
	           }
	        // check if the entered value is less than the maximum limit
	        else if (d > max){
	            System.out.println("Please enter a number less than "+ max);
	           }
	        else
	         validity = true;
	        }
   
	    // returns the integer within range given
	   return d;
	}
	
	
	// prints special message for certain combinations of Random Number of Dice 1 and Dice 2
	private static void specialMessage(int randomOfDice1, int randomOfDice2) {
		
		// print "Snake Eyes!" if the numbers on bith the dice are 1
		if ((randomOfDice1 ==1) && (randomOfDice2==1)) {
			System.out.println("Snake Eyes!");
		}
		// print "Box cars!" if the numbers on both the dice are 6 
		else if(randomOfDice1==6 && randomOfDice2==6) {
			System.out.println("Box Cars!");
		}
		// print "Craps!" if the sum of the numbers on the dice is equal to 7 or 11
		else if (randomOfDice1+randomOfDice2==7 || (randomOfDice1+randomOfDice2 ==11)) {
			System.out.println("Craps!");
		}
		// print "Not so special!" for all other number combinations
		else {
			System.out.println("Not so Special!");
		}

	}
	
	// tried with this initially
	// generates a random number using random() method from the java.lang-Math class
	/*private static int randomGenerator(int numberOfSides) {
		int randomNumber=0;
		randomNumber=(int)(Math.random()*10);
		return randomNumber;
	}
	*/

}
